services:
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    image: api:v1
    container_name: api
    depends_on:
      - database
    networks:
      - backend

  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports:
      - "8883:8883"
    image: broker:v1
    container_name: broker
    volumes:
      - ./broker/certs:/mosquitto/certs:ro
    networks:
      - backend

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database:v1
    container_name: postgres
    networks:
      - backend

  ingestor:
    build:
      context: ./ingestor
    container_name: ingestor
    depends_on:
      - broker
      - database
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
